### ISSUE TITLE
missing dependency collective.z3cform.datagridfield

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.odoo.pas#2]
With Plone 5.0.2 unified installer on macOS Sierra 10.12.2, and collective.odoo.pas master branch, the dependency collective.z3cform.datagridfield needs to be added to buildout.cfg eggs manually but should be specified in setup.py

**Comment by Martronic-SA** [comment]
That was a wrong import!
datagridfield is not needed. 
Fixed by [commit](https://github.com/collective/collective.odoo.pas/commit/37548a40596f92bbcef564806fe8cb4bb7b86f07)
