### ISSUE TITLE
control panel missing navigation to other control panels

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.odoo.pas#6]
The control panel should include the usual right portlet of all other control panels (or at least a link up to Site Setup (@@overview-controlpanel) as on the @@theming-controlpanel).

![controlpanelnav](https://cloud.githubusercontent.com/assets/815418/23334010/c07a5a9e-fb5b-11e6-9257-51be0e2b25ab.png)

**Comment by Martronic-SA** [comment]
Fixed by last commit  (https://github.com/collective/collective.odoo.pas/commit/e97c711a336ffa0c25f82b0f7e582ed39542e0f1)
